/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Compute SipHash-2-4 of a buffer using the default key (0, 0).
 * Returns the 64-bit hash as a BigInt.
 */
export declare function siphash(data: Buffer): bigint

/**
 * Compute SipHash-2-4 of a file at the given path using the default key (0, 0).
 * Reads the file in 8 KiB chunks so large files don't need to fit in memory.
 * Returns the 64-bit hash as a BigInt.
 */
export declare function siphashFile(path: string): bigint

/**
 * Compute SipHash-2-4 of a buffer with a caller-supplied 128-bit key
 * provided as two 64-bit halves (BigInt). Returns the hash as a BigInt.
 */
export declare function siphashWithKey(data: Buffer, key0: bigint, key1: bigint): bigint
